"""Add stock column to Details table

Revision ID: d9983e819268
Revises: 
Create Date: 2025-06-25 10:45:45.149298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9983e819268'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock', sa.Numeric(precision=10, scale=3), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('details', schema=None) as batch_op:
        batch_op.drop_column('stock')

    # ### end Alembic commands ###
